name: Automated Multi-Registry Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: Install Dependencies
        run: pnpm install

      - name: Build All Projects
        run: pnpm build

      - name: Publish to both registries
        run: |
          for pkg in calculator atm todo-list currency-converter word-counter student-management-system adventure-game quiz countdown-timer number-guessing-game oop oop-mybank ghost; do
            cat > dist/$pkg/package.json <<EOF
          {
            "name": "@muhammed_suhaib/$pkg",
            "version": "1.0.${{ github.run_number }}",
            "main": "index.js",
            "type": "module",
            "bin": { "$pkg": "index.js" },
            "dependencies": {
              "chalk": "^5.6.2",
              "chalk-animation": "^2.0.3",
              "figlet": "^1.11.0",
              "inquirer": "^9.3.8",
              "node-banner": "^1.4.0"
            }
          }
          EOF
            cd dist/$pkg

            pnpm config set //registry.npmjs.org/:_authToken "${{ secrets.TYPESCRIPT_NODE_NPM }}"
            pnpm publish --registry=https://registry.npmjs.org --access public --no-git-checks

            cat > package.json <<EOF
          {
            "name": "@muhammedsuhaib/$pkg",
            "version": "1.0.${{ github.run_number }}",
            "main": "index.js",
            "type": "module",
            "bin": { "$pkg": "index.js" },
            "dependencies": {
              "chalk": "^5.6.2",
              "chalk-animation": "^2.0.3",
              "figlet": "^1.11.0",
              "inquirer": "^9.3.8",
              "node-banner": "^1.4.0"
            }
          }
          EOF
            pnpm config set //npm.pkg.github.com/:_authToken "${{ secrets.TYPESCRIPT_NODE_GITHUB_PAT }}"
            pnpm publish --registry=https://npm.pkg.github.com --no-git-checks

            cd ../..
            sleep 25
          done
